name: complex

on: push

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    name: ubuntu
    steps:
      - name: print date
        run: date

  windows:
    runs-on: windows-latest
    name: windows
    steps:
      - name: print date
        run: date

  macos:
    runs-on: macos-latest
    name: macos
    steps:
      - name: print date
        run: date

  ubuntu20:
    runs-on: ubuntu@20.04
    name: ubuntu20
    steps:
      - name: print date
        run: date
    needs: [ubuntu, windows, macos]
